name: Deploy To LiNode US

on:
  push:
    branches: [cicd]
  pull_request:
    branches: [cicd]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: mydist
          path: './*'
  deploy-linode-us:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: mydist
          path: mydist

      - name: deploy to remote server [172.104.215.201]
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          # 服务器私钥
          SSH_PRIVATE_KEY:  ${{ secrets.SSH_PRIVATE_KEY }}
          # Server IP
          REMOTE_HOST:  172.104.215.201
          # Username
          REMOTE_USER:  root
          # Port
          REMOTE_PORT: 22
          # Source Path
          SOURCE: "mydist/"
          # Target Path
          TARGET: "/data/indexer-helper"
          #  rsync
          ARGS: "-rltgoDzvO"
          # An array of folder to exclude
          EXCLUDE: ".git, .github"


      - name: Execute SSH commmands on remote server[172.104.215.201]
        uses: appleboy/ssh-action@master
        with:
          host: 172.104.215.201
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sh /data/indexer-helper/boot.sh restart

      - name: deploy to remote server [45.79.131.6]
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          # Private Key
          SSH_PRIVATE_KEY:  ${{ secrets.SSH_PRIVATE_KEY }}
          # Server IP
          REMOTE_HOST:  45.79.131.6
          # Useranme
          REMOTE_USER:  root
          # Port
          REMOTE_PORT: 22
          # Source Path
          SOURCE: "mydist/"
          # Target Path
          TARGET: "/data/indexer-helper"
          #  rsync
          ARGS: "-rltgoDzvO"
          # An array of folder to exclude
          EXCLUDE: ".git, .github"


      - name: Execute SSH commmands on remote server[45.79.131.6]
        uses: appleboy/ssh-action@master
        with:
          host: 45.79.131.6
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sh /data/indexer-helper/boot.sh restart


